### ISSUE TITLE
Only JSON messages supported

### ISSUE THREAD

**Issue by rubenv** [KardinalAI/gorabbit#9]
Currently marshalling to JSON is baked into the library.

Would you accept a PR where we allow overriding this so that other content types can be used?

**Comment by m3talux** [comment]
Yes, absolutely! That was definitely in the pipe . The only complexity in adding dynamic content would be to find a way to do it without breaking the current method signature. 

I've seen a couple of libraries use variadic functions: `Foo(opts ...Option)` and that would allow updating the existing publishing method without breaking current implementations. My only concern with that is the ability to add an infinite amount of options, while only the first one would be used.

I'm open to suggestions regarding this matter.
